var bs_data=[
    {
        "desc":"Acidimangrovimonas sediminis strain MS2-2",
        "end":41071,
        "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":79.2,
                        "code":"PF07690",
                        "end":410,
                        "start":33
                    }
                ],
                "end":1487,
                "id":"proP_2",
                "start":116,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.1,
                        "code":"PF02627",
                        "end":120,
                        "start":36
                    }
                ],
                "end":2031,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF2",
                "start":1575,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":512.0,
                        "code":"PF00171",
                        "end":470,
                        "start":13
                    }
                ],
                "end":3528,
                "id":"ald_1",
                "start":2097,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":125.9,
                        "code":"PF14833",
                        "end":286,
                        "start":165
                    },
                    {
                        "bitscore":132.8,
                        "code":"PF03446",
                        "end":162,
                        "start":5
                    }
                ],
                "end":4408,
                "id":"garR_1",
                "start":3532,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":89.2,
                        "code":"PF07978",
                        "end":106,
                        "start":3
                    }
                ],
                "end":4783,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF5",
                "start":4456,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.1,
                        "code":"PF00753",
                        "end":242,
                        "start":35
                    }
                ],
                "end":5619,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF6",
                "start":4809,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":97.2,
                        "code":"PF03625",
                        "end":99,
                        "start":36
                    }
                ],
                "end":6698,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF7",
                "start":6302,
                "strand":-1
            },
            {
                "domains":[],
                "end":8015,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF8",
                "start":7055,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":37.4,
                        "code":"PF09851",
                        "end":106,
                        "start":79
                    }
                ],
                "end":8505,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF9",
                "start":8181,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.9,
                        "code":"PF00034",
                        "end":153,
                        "start":69
                    }
                ],
                "end":9082,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF10",
                "start":8602,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":144.5,
                        "code":"PF00702",
                        "end":678,
                        "start":462
                    },
                    {
                        "bitscore":172.4,
                        "code":"PF00122",
                        "end":446,
                        "start":263
                    },
                    {
                        "bitscore":48.7,
                        "code":"PF19335",
                        "end":108,
                        "start":81
                    },
                    {
                        "bitscore":38.5,
                        "code":"PF04945",
                        "end":68,
                        "start":21
                    }
                ],
                "end":11437,
                "id":"actP_2",
                "start":9100,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":136.4,
                        "code":"PF00248",
                        "end":324,
                        "start":10
                    }
                ],
                "end":12701,
                "id":"fdh",
                "start":11696,
                "strand":1
            },
            {
                "domains":[],
                "end":12925,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF13",
                "start":12775,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.3,
                        "code":"PF00107",
                        "end":168,
                        "start":78
                    }
                ],
                "end":13654,
                "id":"tdh_1",
                "start":13111,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":150.5,
                        "code":"PF00106",
                        "end":186,
                        "start":2
                    }
                ],
                "end":14538,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF15",
                "start":13779,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":107.8,
                        "code":"PF12852",
                        "end":185,
                        "start":7
                    },
                    {
                        "bitscore":71.4,
                        "code":"PF12833",
                        "end":299,
                        "start":221
                    }
                ],
                "end":15546,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF16",
                "start":14634,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.5,
                        "code":"PF04542",
                        "end":92,
                        "start":24
                    },
                    {
                        "bitscore":41.6,
                        "code":"PF08281",
                        "end":176,
                        "start":123
                    }
                ],
                "end":16497,
                "id":"sigK_1",
                "start":15948,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.3,
                        "code":"PF10099",
                        "end":221,
                        "start":65
                    }
                ],
                "end":17177,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF18",
                "start":16493,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":107.0,
                        "code":"PF02469",
                        "end":181,
                        "start":46
                    }
                ],
                "end":17853,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF19",
                "start":17301,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.6,
                        "code":"PF01292",
                        "end":257,
                        "start":4
                    }
                ],
                "end":18759,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF20",
                "start":17943,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":151.8,
                        "code":"PF00174",
                        "end":247,
                        "start":86
                    }
                ],
                "end":19536,
                "id":"yedY1",
                "start":18759,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.4,
                        "code":"PF13564",
                        "end":122,
                        "start":18
                    }
                ],
                "end":19891,
                "id":"yqjF",
                "start":19513,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":66.6,
                        "code":"PF00195",
                        "end":203,
                        "start":66
                    },
                    {
                        "bitscore":59.5,
                        "code":"PF02797",
                        "end":345,
                        "start":210
                    }
                ],
                "end":21071,
                "id":"rppA",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.5,
                        "code":"PF04140",
                        "end":165,
                        "start":74
                    }
                ],
                "end":21577,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF24",
                "start":21067,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":320.3,
                        "code":"PF06808",
                        "end":424,
                        "start":11
                    }
                ],
                "end":23112,
                "id":"dctM_5",
                "start":21804,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":83.9,
                        "code":"PF04290",
                        "end":160,
                        "start":28
                    }
                ],
                "end":23603,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF26",
                "start":23108,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":153.1,
                        "code":"PF03480",
                        "end":313,
                        "start":29
                    }
                ],
                "end":24605,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF27",
                "start":23618,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":246.9,
                        "code":"PF03437",
                        "end":264,
                        "start":9
                    }
                ],
                "end":25802,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF28",
                "start":24998,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.4,
                        "code":"PF00528",
                        "end":287,
                        "start":80
                    }
                ],
                "end":26735,
                "id":"melD_2",
                "start":25871,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":112.9,
                        "code":"PF01547",
                        "end":339,
                        "start":33
                    }
                ],
                "end":28106,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF30",
                "start":26834,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.5,
                        "code":"PF00528",
                        "end":262,
                        "start":77
                    }
                ],
                "end":28951,
                "id":"sugB",
                "start":28150,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":34.9,
                        "code":"PF08402",
                        "end":354,
                        "start":283
                    },
                    {
                        "bitscore":118.8,
                        "code":"PF00005",
                        "end":163,
                        "start":20
                    }
                ],
                "end":30054,
                "id":"msmX_1",
                "start":28953,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":210.2,
                        "code":"PF13561",
                        "end":264,
                        "start":23
                    }
                ],
                "end":30921,
                "id":"fabG_3",
                "start":30120,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":76.5,
                        "code":"PF08220",
                        "end":76,
                        "start":21
                    },
                    {
                        "bitscore":129.6,
                        "code":"PF00455",
                        "end":255,
                        "start":95
                    }
                ],
                "end":31889,
                "id":"glpR_2",
                "start":31061,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":173.3,
                        "code":"PF00370",
                        "end":247,
                        "start":3
                    },
                    {
                        "bitscore":108.8,
                        "code":"PF02782",
                        "end":447,
                        "start":264
                    }
                ],
                "end":33391,
                "id":"xylB_1",
                "start":31906,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":85.5,
                        "code":"PF13419",
                        "end":183,
                        "start":6
                    }
                ],
                "end":34029,
                "id":"ppaX",
                "start":33387,
                "strand":1
            },
            {
                "domains":[],
                "end":34530,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF37",
                "start":34371,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":270.5,
                        "code":"PF06808",
                        "end":429,
                        "start":11
                    }
                ],
                "end":35857,
                "id":"dctM_6",
                "start":34540,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.0,
                        "code":"PF04290",
                        "end":164,
                        "start":30
                    }
                ],
                "end":36368,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF39",
                "start":35846,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":120.8,
                        "code":"PF03480",
                        "end":322,
                        "start":30
                    }
                ],
                "end":37507,
                "id":"GCF_002871005.1_Acidimangrovimonas_sediminis_MS2-2-NZ_PHSN01000014.1.region001_ORF41",
                "start":36472,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":55.7,
                        "code":"PF00392",
                        "end":73,
                        "start":11
                    },
                    {
                        "bitscore":79.1,
                        "code":"PF07729",
                        "end":207,
                        "start":83
                    }
                ],
                "end":38339,
                "id":"rspR_3",
                "start":37667,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":96.6,
                        "code":"PF03737",
                        "end":173,
                        "start":10
                    }
                ],
                "end":39153,
                "id":"ligK_2",
                "start":38484,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.2,
                        "code":"PF00528",
                        "end":255,
                        "start":77
                    }
                ],
                "end":39963,
                "id":"phnV_2",
                "start":39171,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":63.2,
                        "code":"PF00528",
                        "end":299,
                        "start":128
                    }
                ],
                "end":40872,
                "id":"potH",
                "start":39972,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Frigidibacter albus strain SP32",
        "end":52932,
        "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":106.6,
                        "code":"PF00005",
                        "end":165,
                        "start":17
                    }
                ],
                "end":831,
                "id":"mkl_2",
                "start":84,
                "strand":1
            },
            {
                "domains":[],
                "end":1724,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF2",
                "start":962,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.7,
                        "code":"PF04403",
                        "end":146,
                        "start":4
                    }
                ],
                "end":2171,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF3",
                "start":1730,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":53.0,
                        "code":"PF16576",
                        "end":1037,
                        "start":754
                    }
                ],
                "end":5571,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF4",
                "start":2361,
                "strand":1
            },
            {
                "domains":[],
                "end":6747,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF5",
                "start":5679,
                "strand":-1
            },
            {
                "domains":[],
                "end":7129,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF6",
                "start":6841,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.1,
                        "code":"PF08241",
                        "end":151,
                        "start":39
                    }
                ],
                "end":8060,
                "id":"COQ5_3",
                "start":7172,
                "strand":-1
            },
            {
                "domains":[],
                "end":9003,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF8",
                "start":8049,
                "strand":-1
            },
            {
                "domains":[],
                "end":10534,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF9",
                "start":9007,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":177.9,
                        "code":"PF00106",
                        "end":200,
                        "start":7
                    }
                ],
                "end":11273,
                "id":"rbtD",
                "start":10538,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":146.6,
                        "code":"PF00106",
                        "end":204,
                        "start":5
                    }
                ],
                "end":12060,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF11",
                "start":11301,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":76.0,
                        "code":"PF00561",
                        "end":160,
                        "start":25
                    }
                ],
                "end":13178,
                "id":"rutD_2",
                "start":12056,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":142.8,
                        "code":"PF01663",
                        "end":452,
                        "start":25
                    }
                ],
                "end":14855,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF13",
                "start":13217,
                "strand":-1
            },
            {
                "domains":[],
                "end":15407,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF14",
                "start":15044,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":28.8,
                        "code":"PF13469",
                        "end":231,
                        "start":9
                    }
                ],
                "end":16349,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF15",
                "start":15434,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.4,
                        "code":"PF10503",
                        "end":194,
                        "start":66
                    }
                ],
                "end":17369,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF16",
                "start":16367,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":87.3,
                        "code":"PF13469",
                        "end":219,
                        "start":4
                    }
                ],
                "end":18622,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF17",
                "start":17737,
                "strand":1
            },
            {
                "domains":[],
                "end":19997,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF18",
                "start":18626,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":30.4,
                        "code":"PF01648",
                        "end":1576,
                        "start":1477
                    },
                    {
                        "bitscore":76.3,
                        "code":"PF14765",
                        "end":1324,
                        "start":1023
                    },
                    {
                        "bitscore":61.1,
                        "code":"PF00698",
                        "end":902,
                        "start":569
                    },
                    {
                        "bitscore":40.5,
                        "code":"PF16197",
                        "end":525,
                        "start":418
                    },
                    {
                        "bitscore":108.4,
                        "code":"PF02801",
                        "end":415,
                        "start":296
                    },
                    {
                        "bitscore":180.1,
                        "code":"PF00109",
                        "end":288,
                        "start":10
                    }
                ],
                "end":24764,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF19",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.8,
                        "code":"PF14765",
                        "end":2700,
                        "start":2415
                    },
                    {
                        "bitscore":121.4,
                        "code":"PF08659",
                        "end":2343,
                        "start":2118
                    },
                    {
                        "bitscore":104.5,
                        "code":"PF00698",
                        "end":1549,
                        "start":1249
                    },
                    {
                        "bitscore":110.8,
                        "code":"PF02801",
                        "end":1080,
                        "start":964
                    },
                    {
                        "bitscore":227.2,
                        "code":"PF00109",
                        "end":956,
                        "start":687
                    }
                ],
                "end":32932,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF20",
                "start":24760,
                "strand":-1
            },
            {
                "domains":[],
                "end":33840,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF21",
                "start":33000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.9,
                        "code":"PF00884",
                        "end":276,
                        "start":3
                    }
                ],
                "end":34722,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF22",
                "start":33861,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":17.5,
                        "code":"PF13176",
                        "end":325,
                        "start":290
                    },
                    {
                        "bitscore":32.2,
                        "code":"PF13432",
                        "end":218,
                        "start":154
                    },
                    {
                        "bitscore":40.2,
                        "code":"PF13432",
                        "end":83,
                        "start":18
                    }
                ],
                "end":35902,
                "id":"bepA_4",
                "start":34750,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":37.0,
                        "code":"PF18073",
                        "end":36,
                        "start":9
                    },
                    {
                        "bitscore":51.1,
                        "code":"PF13481",
                        "end":220,
                        "start":69
                    },
                    {
                        "bitscore":38.1,
                        "code":"PF13541",
                        "end":427,
                        "start":314
                    }
                ],
                "end":37588,
                "id":"radA",
                "start":36223,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.1,
                        "code":"PF02674",
                        "end":157,
                        "start":7
                    }
                ],
                "end":38266,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF25",
                "start":37648,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.9,
                        "code":"PF13537",
                        "end":221,
                        "start":92
                    }
                ],
                "end":39991,
                "id":"purF_2",
                "start":38530,
                "strand":1
            },
            {
                "domains":[],
                "end":41341,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF27",
                "start":40063,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.9,
                        "code":"PF00106",
                        "end":210,
                        "start":18
                    }
                ],
                "end":42117,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF28",
                "start":41430,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":163.8,
                        "code":"PF01975",
                        "end":198,
                        "start":3
                    }
                ],
                "end":43016,
                "id":"surE",
                "start":42230,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":187.5,
                        "code":"PF01135",
                        "end":217,
                        "start":12
                    }
                ],
                "end":43672,
                "id":"pcm_2",
                "start":43012,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":23.4,
                        "code":"PF01476",
                        "end":131,
                        "start":91
                    },
                    {
                        "bitscore":38.1,
                        "code":"PF01476",
                        "end":227,
                        "start":184
                    },
                    {
                        "bitscore":62.0,
                        "code":"PF01551",
                        "end":398,
                        "start":306
                    }
                ],
                "end":44949,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF31",
                "start":43737,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":344.4,
                        "code":"PF05673",
                        "end":276,
                        "start":27
                    }
                ],
                "end":46031,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF32",
                "start":45188,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":220.5,
                        "code":"PF00902",
                        "end":252,
                        "start":16
                    }
                ],
                "end":46909,
                "id":"tatC",
                "start":46027,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.2,
                        "code":"PF02416",
                        "end":86,
                        "start":4
                    }
                ],
                "end":47547,
                "id":"tatB",
                "start":46905,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.9,
                        "code":"PF02416",
                        "end":84,
                        "start":5
                    }
                ],
                "end":47876,
                "id":"tatA_2",
                "start":47615,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":28.6,
                        "code":"PF08402",
                        "end":368,
                        "start":285
                    },
                    {
                        "bitscore":110.1,
                        "code":"PF00005",
                        "end":178,
                        "start":34
                    }
                ],
                "end":49417,
                "id":"btuD_15",
                "start":48298,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":49.6,
                        "code":"PF00300",
                        "end":187,
                        "start":9
                    }
                ],
                "end":50511,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF37",
                "start":49899,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":134.2,
                        "code":"PF00106",
                        "end":197,
                        "start":8
                    }
                ],
                "end":51299,
                "id":"fabG_10",
                "start":50522,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.1,
                        "code":"PF13403",
                        "end":295,
                        "start":156
                    }
                ],
                "end":52536,
                "id":"GCF_009908165.1_Frigidibacter_albus_SP32-NZ_JAAAUC010000008.1.region001_ORF39",
                "start":51495,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"NZ_JAFMPR010000003.1 Roseibaca sp. Y0-43 scaffold_3_length=351146, whole genome shotgun sequence",
        "end":41041,
        "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":897,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF1",
                "start":300,
                "strand":-1
            },
            {
                "domains":[],
                "end":1965,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF2",
                "start":918,
                "strand":-1
            },
            {
                "domains":[],
                "end":2489,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF3",
                "start":2093,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":78.4,
                        "code":"PF14579",
                        "end":889,
                        "start":801
                    },
                    {
                        "bitscore":212.0,
                        "code":"PF17657",
                        "end":728,
                        "start":566
                    },
                    {
                        "bitscore":340.1,
                        "code":"PF07733",
                        "end":563,
                        "start":298
                    },
                    {
                        "bitscore":114.8,
                        "code":"PF02811",
                        "end":178,
                        "start":9
                    }
                ],
                "end":6689,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF4",
                "start":3251,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":119.1,
                        "code":"PF00005",
                        "end":168,
                        "start":23
                    },
                    {
                        "bitscore":35.4,
                        "code":"PF00005",
                        "end":429,
                        "start":272
                    }
                ],
                "end":8377,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF5",
                "start":6844,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":127.7,
                        "code":"PF02653",
                        "end":343,
                        "start":63
                    }
                ],
                "end":9459,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF6",
                "start":8373,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":126.0,
                        "code":"PF02653",
                        "end":286,
                        "start":11
                    }
                ],
                "end":10388,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF7",
                "start":9455,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":141.3,
                        "code":"PF02608",
                        "end":307,
                        "start":27
                    }
                ],
                "end":11506,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF8",
                "start":10426,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.2,
                        "code":"PF01734",
                        "end":167,
                        "start":7
                    }
                ],
                "end":12473,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF9",
                "start":11555,
                "strand":-1
            },
            {
                "domains":[],
                "end":13171,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF10",
                "start":12577,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":152.5,
                        "code":"PF01556",
                        "end":342,
                        "start":128
                    },
                    {
                        "bitscore":91.8,
                        "code":"PF00226",
                        "end":67,
                        "start":5
                    }
                ],
                "end":14319,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF11",
                "start":13167,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":900.7,
                        "code":"PF00012",
                        "end":600,
                        "start":4
                    }
                ],
                "end":16308,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF12",
                "start":14391,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":357.2,
                        "code":"PF01432",
                        "end":666,
                        "start":223
                    }
                ],
                "end":18473,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF13",
                "start":16466,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.2,
                        "code":"PF07690",
                        "end":410,
                        "start":203
                    },
                    {
                        "bitscore":33.5,
                        "code":"PF07690",
                        "end":203,
                        "start":11
                    }
                ],
                "end":19804,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF14",
                "start":18529,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":82.4,
                        "code":"PF00195",
                        "end":203,
                        "start":2
                    },
                    {
                        "bitscore":59.9,
                        "code":"PF02797",
                        "end":343,
                        "start":207
                    }
                ],
                "end":21041,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF15",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":81.9,
                        "code":"PF04140",
                        "end":160,
                        "start":69
                    }
                ],
                "end":21526,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF16",
                "start":21037,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":76.1,
                        "code":"PF01370",
                        "end":239,
                        "start":3
                    }
                ],
                "end":22446,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF17",
                "start":21552,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.2,
                        "code":"PF08669",
                        "end":818,
                        "start":739
                    },
                    {
                        "bitscore":233.4,
                        "code":"PF01571",
                        "end":718,
                        "start":438
                    },
                    {
                        "bitscore":51.3,
                        "code":"PF16350",
                        "end":436,
                        "start":382
                    },
                    {
                        "bitscore":192.5,
                        "code":"PF01266",
                        "end":379,
                        "start":6
                    }
                ],
                "end":24936,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF18",
                "start":22449,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":13.6,
                        "code":"PF13202",
                        "end":153,
                        "start":132
                    },
                    {
                        "bitscore":13.3,
                        "code":"PF13202",
                        "end":131,
                        "start":115
                    }
                ],
                "end":25527,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF19",
                "start":25062,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":324.0,
                        "code":"PF02569",
                        "end":274,
                        "start":2
                    }
                ],
                "end":26506,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF20",
                "start":25660,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":350.0,
                        "code":"PF02548",
                        "end":264,
                        "start":9
                    }
                ],
                "end":27312,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF21",
                "start":26502,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":168.8,
                        "code":"PF00800",
                        "end":182,
                        "start":5
                    }
                ],
                "end":28164,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF22",
                "start":27330,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.2,
                        "code":"PF00034",
                        "end":168,
                        "start":71
                    }
                ],
                "end":28791,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF23",
                "start":28284,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":220.0,
                        "code":"PF00496",
                        "end":535,
                        "start":114
                    }
                ],
                "end":30882,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF24",
                "start":28983,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":117.2,
                        "code":"PF00528",
                        "end":357,
                        "start":145
                    }
                ],
                "end":31974,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF25",
                "start":30885,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.5,
                        "code":"PF12911",
                        "end":75,
                        "start":19
                    },
                    {
                        "bitscore":101.8,
                        "code":"PF00528",
                        "end":382,
                        "start":173
                    }
                ],
                "end":33129,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF26",
                "start":31977,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.6,
                        "code":"PF00005",
                        "end":181,
                        "start":23
                    },
                    {
                        "bitscore":26.6,
                        "code":"PF08352",
                        "end":262,
                        "start":232
                    },
                    {
                        "bitscore":108.7,
                        "code":"PF00005",
                        "end":449,
                        "start":298
                    },
                    {
                        "bitscore":22.9,
                        "code":"PF08352",
                        "end":530,
                        "start":500
                    }
                ],
                "end":34727,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF27",
                "start":33125,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":178.6,
                        "code":"PF12000",
                        "end":194,
                        "start":24
                    },
                    {
                        "bitscore":55.1,
                        "code":"PF00534",
                        "end":382,
                        "start":205
                    }
                ],
                "end":35955,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF28",
                "start":34740,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":122.5,
                        "code":"PF16867",
                        "end":207,
                        "start":49
                    }
                ],
                "end":36653,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF29",
                "start":35951,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.1,
                        "code":"PF00444",
                        "end":41,
                        "start":1
                    }
                ],
                "end":36861,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF30",
                "start":36735,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":214.4,
                        "code":"PF05013",
                        "end":243,
                        "start":14
                    }
                ],
                "end":38006,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF31",
                "start":37151,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":165.6,
                        "code":"PF00999",
                        "end":418,
                        "start":4
                    },
                    {
                        "bitscore":60.6,
                        "code":"PF00027",
                        "end":807,
                        "start":725
                    }
                ],
                "end":40565,
                "id":"GCF_020667835.1_Roseibaca_sp._Y0-43_Y0-43-NZ_JAFMPR010000003.1.region001_ORF32",
                "start":38054,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Roseibaca sp.v10 strain V10",
        "end":41041,
        "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":149.6,
                        "code":"PF00497",
                        "end":264,
                        "start":42
                    }
                ],
                "end":1480,
                "id":"fliY",
                "start":652,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.1,
                        "code":"PF00528",
                        "end":275,
                        "start":93
                    }
                ],
                "end":2336,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF2",
                "start":1499,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":94.4,
                        "code":"PF02348",
                        "end":242,
                        "start":5
                    }
                ],
                "end":3277,
                "id":"kdsB_1",
                "start":2461,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":221.3,
                        "code":"PF00793",
                        "end":274,
                        "start":2
                    }
                ],
                "end":4110,
                "id":"kdsA",
                "start":3273,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":77.8,
                        "code":"PF14579",
                        "end":889,
                        "start":801
                    },
                    {
                        "bitscore":209.2,
                        "code":"PF17657",
                        "end":728,
                        "start":566
                    },
                    {
                        "bitscore":340.1,
                        "code":"PF07733",
                        "end":563,
                        "start":298
                    },
                    {
                        "bitscore":112.6,
                        "code":"PF02811",
                        "end":178,
                        "start":9
                    }
                ],
                "end":7615,
                "id":"dnaE1",
                "start":4177,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":117.6,
                        "code":"PF00005",
                        "end":168,
                        "start":23
                    },
                    {
                        "bitscore":33.2,
                        "code":"PF00005",
                        "end":429,
                        "start":272
                    }
                ],
                "end":9310,
                "id":"mglA",
                "start":7777,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":129.5,
                        "code":"PF02653",
                        "end":343,
                        "start":63
                    }
                ],
                "end":10392,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF7",
                "start":9306,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":123.3,
                        "code":"PF02653",
                        "end":286,
                        "start":11
                    }
                ],
                "end":11321,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF8",
                "start":10388,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":137.9,
                        "code":"PF02608",
                        "end":309,
                        "start":26
                    }
                ],
                "end":12434,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF9",
                "start":11357,
                "strand":1
            },
            {
                "domains":[],
                "end":13128,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF10",
                "start":12531,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":142.8,
                        "code":"PF01556",
                        "end":344,
                        "start":130
                    },
                    {
                        "bitscore":89.7,
                        "code":"PF00226",
                        "end":67,
                        "start":5
                    }
                ],
                "end":14282,
                "id":"dnaJ",
                "start":13124,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":896.7,
                        "code":"PF00012",
                        "end":600,
                        "start":4
                    }
                ],
                "end":16267,
                "id":"dnaK",
                "start":14353,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":349.9,
                        "code":"PF01432",
                        "end":666,
                        "start":223
                    }
                ],
                "end":18442,
                "id":"dcp",
                "start":16435,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":71.2,
                        "code":"PF07690",
                        "end":408,
                        "start":203
                    },
                    {
                        "bitscore":24.9,
                        "code":"PF00083",
                        "end":185,
                        "start":9
                    }
                ],
                "end":19804,
                "id":"ycaD_1",
                "start":18508,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":75.8,
                        "code":"PF00195",
                        "end":203,
                        "start":2
                    },
                    {
                        "bitscore":62.4,
                        "code":"PF02797",
                        "end":344,
                        "start":207
                    }
                ],
                "end":21041,
                "id":"rppA",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":78.6,
                        "code":"PF04140",
                        "end":160,
                        "start":69
                    }
                ],
                "end":21526,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF16",
                "start":21037,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":80.1,
                        "code":"PF01370",
                        "end":239,
                        "start":3
                    }
                ],
                "end":22490,
                "id":"galE_1",
                "start":21596,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":60.3,
                        "code":"PF08669",
                        "end":818,
                        "start":739
                    },
                    {
                        "bitscore":233.5,
                        "code":"PF01571",
                        "end":718,
                        "start":438
                    },
                    {
                        "bitscore":51.1,
                        "code":"PF16350",
                        "end":436,
                        "start":382
                    },
                    {
                        "bitscore":195.2,
                        "code":"PF01266",
                        "end":379,
                        "start":6
                    }
                ],
                "end":24980,
                "id":"abo_1",
                "start":22493,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":17.8,
                        "code":"PF13202",
                        "end":153,
                        "start":132
                    },
                    {
                        "bitscore":11.9,
                        "code":"PF13202",
                        "end":131,
                        "start":115
                    },
                    {
                        "bitscore":23.6,
                        "code":"PF13202",
                        "end":73,
                        "start":49
                    }
                ],
                "end":25572,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF19",
                "start":25110,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":319.9,
                        "code":"PF02569",
                        "end":274,
                        "start":2
                    }
                ],
                "end":26545,
                "id":"panC",
                "start":25699,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":345.6,
                        "code":"PF02548",
                        "end":264,
                        "start":9
                    }
                ],
                "end":27351,
                "id":"panB",
                "start":26541,
                "strand":1
            },
            {
                "domains":[],
                "end":28169,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF22",
                "start":27371,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":158.1,
                        "code":"PF13561",
                        "end":258,
                        "start":14
                    }
                ],
                "end":29527,
                "id":"bacC_1",
                "start":28720,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":135.6,
                        "code":"PF05175",
                        "end":331,
                        "start":166
                    }
                ],
                "end":30546,
                "id":"rsmC",
                "start":29523,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":117.0,
                        "code":"PF02617",
                        "end":107,
                        "start":28
                    }
                ],
                "end":30891,
                "id":"clpS",
                "start":30555,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":27.4,
                        "code":"PF00702",
                        "end":189,
                        "start":4
                    }
                ],
                "end":31688,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF26",
                "start":30983,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":202.0,
                        "code":"PF00768",
                        "end":252,
                        "start":21
                    }
                ],
                "end":33771,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF27",
                "start":31863,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":45.1,
                        "code":"PF00892",
                        "end":283,
                        "start":146
                    },
                    {
                        "bitscore":71.9,
                        "code":"PF00892",
                        "end":138,
                        "start":3
                    }
                ],
                "end":34646,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF28",
                "start":33767,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":23.8,
                        "code":"PF00034",
                        "end":139,
                        "start":26
                    }
                ],
                "end":35294,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF29",
                "start":34868,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.0,
                        "code":"PF08245",
                        "end":264,
                        "start":47
                    }
                ],
                "end":36619,
                "id":"folC",
                "start":35350,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":54.3,
                        "code":"PF01039",
                        "end":287,
                        "start":85
                    },
                    {
                        "bitscore":32.3,
                        "code":"PF17848",
                        "end":51,
                        "start":26
                    }
                ],
                "end":37526,
                "id":"accD",
                "start":36620,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.0,
                        "code":"PF02517",
                        "end":242,
                        "start":139
                    }
                ],
                "end":38473,
                "id":"GCF_023336755.1_Roseibaca_sp.V10_V10-NZ_JALZWP010000002.1.region001_ORF32",
                "start":37582,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.4,
                        "code":"PF13396",
                        "end":54,
                        "start":11
                    },
                    {
                        "bitscore":46.1,
                        "code":"PF13091",
                        "end":271,
                        "start":124
                    },
                    {
                        "bitscore":74.3,
                        "code":"PF13091",
                        "end":442,
                        "start":315
                    }
                ],
                "end":40011,
                "id":"clsA",
                "start":38583,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Roseibaca ekhonensis strain CECT7235",
        "end":41041,
        "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":51.6,
                        "code":"PF03150",
                        "end":104,
                        "start":59
                    }
                ],
                "end":584,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF1",
                "start":269,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":75.7,
                        "code":"PF03150",
                        "end":97,
                        "start":1
                    },
                    {
                        "bitscore":25.8,
                        "code":"PF00034",
                        "end":210,
                        "start":103
                    }
                ],
                "end":1277,
                "id":"ccpA",
                "start":608,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.7,
                        "code":"PF13091",
                        "end":441,
                        "start":315
                    },
                    {
                        "bitscore":49.6,
                        "code":"PF13091",
                        "end":271,
                        "start":124
                    },
                    {
                        "bitscore":31.0,
                        "code":"PF13396",
                        "end":54,
                        "start":13
                    }
                ],
                "end":2766,
                "id":"clsA",
                "start":1338,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.5,
                        "code":"PF02517",
                        "end":242,
                        "start":139
                    }
                ],
                "end":3767,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF4",
                "start":2876,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.2,
                        "code":"PF17848",
                        "end":51,
                        "start":26
                    },
                    {
                        "bitscore":49.2,
                        "code":"PF01039",
                        "end":285,
                        "start":85
                    }
                ],
                "end":4732,
                "id":"accD",
                "start":3823,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":35.6,
                        "code":"PF08245",
                        "end":264,
                        "start":47
                    }
                ],
                "end":6002,
                "id":"folC",
                "start":4733,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":22.2,
                        "code":"PF00034",
                        "end":139,
                        "start":26
                    }
                ],
                "end":6485,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF7",
                "start":6059,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.2,
                        "code":"PF00892",
                        "end":138,
                        "start":3
                    },
                    {
                        "bitscore":44.1,
                        "code":"PF00892",
                        "end":283,
                        "start":146
                    }
                ],
                "end":7586,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF8",
                "start":6707,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":23.2,
                        "code":"PF05036",
                        "end":643,
                        "start":567
                    },
                    {
                        "bitscore":197.8,
                        "code":"PF00768",
                        "end":252,
                        "start":20
                    }
                ],
                "end":9517,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF9",
                "start":7582,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":31.2,
                        "code":"PF00702",
                        "end":189,
                        "start":4
                    }
                ],
                "end":10395,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF10",
                "start":9690,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":117.0,
                        "code":"PF02617",
                        "end":107,
                        "start":28
                    }
                ],
                "end":10821,
                "id":"clpS",
                "start":10485,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":142.5,
                        "code":"PF05175",
                        "end":331,
                        "start":166
                    }
                ],
                "end":11853,
                "id":"rsmC",
                "start":10830,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":156.4,
                        "code":"PF13561",
                        "end":259,
                        "start":14
                    }
                ],
                "end":12659,
                "id":"bacC_1",
                "start":11849,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.8,
                        "code":"PF00903",
                        "end":104,
                        "start":4
                    }
                ],
                "end":13069,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF14",
                "start":12754,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":345.6,
                        "code":"PF02548",
                        "end":264,
                        "start":9
                    }
                ],
                "end":13882,
                "id":"panB",
                "start":13072,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":323.3,
                        "code":"PF02569",
                        "end":274,
                        "start":2
                    }
                ],
                "end":14724,
                "id":"panC",
                "start":13884,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":16.9,
                        "code":"PF13202",
                        "end":73,
                        "start":49
                    }
                ],
                "end":15302,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF17",
                "start":14852,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":183.8,
                        "code":"PF01266",
                        "end":380,
                        "start":6
                    },
                    {
                        "bitscore":58.3,
                        "code":"PF16350",
                        "end":437,
                        "start":383
                    },
                    {
                        "bitscore":232.9,
                        "code":"PF01571",
                        "end":722,
                        "start":439
                    },
                    {
                        "bitscore":59.4,
                        "code":"PF08669",
                        "end":822,
                        "start":743
                    }
                ],
                "end":17930,
                "id":"abo",
                "start":15431,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.7,
                        "code":"PF01370",
                        "end":239,
                        "start":3
                    }
                ],
                "end":18827,
                "id":"galE_3",
                "start":17933,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":36.8,
                        "code":"PF20327",
                        "end":159,
                        "start":1
                    }
                ],
                "end":19379,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF20",
                "start":18899,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":81.9,
                        "code":"PF04140",
                        "end":160,
                        "start":69
                    }
                ],
                "end":20004,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF21",
                "start":19515,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.1,
                        "code":"PF02797",
                        "end":343,
                        "start":207
                    },
                    {
                        "bitscore":80.7,
                        "code":"PF00195",
                        "end":206,
                        "start":45
                    }
                ],
                "end":21041,
                "id":"rppA",
                "start":20000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":25.5,
                        "code":"PF00083",
                        "end":181,
                        "start":9
                    },
                    {
                        "bitscore":71.7,
                        "code":"PF07690",
                        "end":408,
                        "start":203
                    }
                ],
                "end":22545,
                "id":"ycaD_1",
                "start":21246,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":349.6,
                        "code":"PF01432",
                        "end":666,
                        "start":223
                    }
                ],
                "end":24630,
                "id":"dcp",
                "start":22623,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":894.8,
                        "code":"PF00012",
                        "end":600,
                        "start":4
                    }
                ],
                "end":26714,
                "id":"dnaK_1",
                "start":24797,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.9,
                        "code":"PF00226",
                        "end":67,
                        "start":5
                    },
                    {
                        "bitscore":148.5,
                        "code":"PF01556",
                        "end":344,
                        "start":130
                    }
                ],
                "end":27944,
                "id":"dnaJ",
                "start":26786,
                "strand":1
            },
            {
                "domains":[],
                "end":28537,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF27",
                "start":27940,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":139.7,
                        "code":"PF02608",
                        "end":309,
                        "start":26
                    }
                ],
                "end":29711,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF28",
                "start":28634,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":123.5,
                        "code":"PF02653",
                        "end":286,
                        "start":11
                    }
                ],
                "end":30679,
                "id":"rfuD_2",
                "start":29746,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":130.9,
                        "code":"PF02653",
                        "end":343,
                        "start":63
                    }
                ],
                "end":31761,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF30",
                "start":30675,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":33.4,
                        "code":"PF00005",
                        "end":429,
                        "start":272
                    },
                    {
                        "bitscore":116.6,
                        "code":"PF00005",
                        "end":168,
                        "start":23
                    }
                ],
                "end":33290,
                "id":"mglA",
                "start":31757,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":117.2,
                        "code":"PF02811",
                        "end":178,
                        "start":9
                    },
                    {
                        "bitscore":336.4,
                        "code":"PF07733",
                        "end":563,
                        "start":298
                    },
                    {
                        "bitscore":211.2,
                        "code":"PF17657",
                        "end":728,
                        "start":566
                    },
                    {
                        "bitscore":81.2,
                        "code":"PF14579",
                        "end":889,
                        "start":801
                    }
                ],
                "end":36890,
                "id":"dnaE1",
                "start":33452,
                "strand":1
            },
            {
                "domains":[],
                "end":38160,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF33",
                "start":37752,
                "strand":1
            },
            {
                "domains":[],
                "end":39342,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF34",
                "start":38295,
                "strand":1
            },
            {
                "domains":[],
                "end":39972,
                "id":"GCF_900499075.1_Roseibaca_ekhonensis_CECT_7235-NZ_UIHC01000006.1.region001_ORF35",
                "start":39363,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":220.5,
                        "code":"PF00793",
                        "end":274,
                        "start":3
                    }
                ],
                "end":40883,
                "id":"kdsA",
                "start":40046,
                "strand":1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
